---
- name: 'First playbook'
  hosts: webservers
  remote_user: contenedor
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: 'Task 1'
      timezone:
        name: "{{ zone }}"

    - name: 'Task 2'
      yum:
        name: "{{ rpms }}"
        state: latest